#pragma once

#define DBG_DISABLE_ALL_MOTORS     ( 1 )
#define DBG_DISABLE_ARM_MOTORS     ( 0 || DBG_DISABLE_ALL_MOTORS )
#define DBG_DISABLE_CLIMB_MOTORS   ( 0 || DBG_DISABLE_ALL_MOTORS )
#define DBG_DISABLE_SHOOT_MOTORS   ( 0 || DBG_DISABLE_ALL_MOTORS )
#define DBG_DISABLE_INTAKE_MOTORS  ( 0 || DBG_DISABLE_ALL_MOTORS )
